-- Trek Ships

model = ModelData()
model:setName("space_station_5")
model:setMesh("starbase.model")
model:setTexture("starbase.png")
model:setSpecular("starbase_spec.png")
model:setIllumination("starbase_glow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(20)
model:setRadius(600)
model:setCollisionBox(350, 350)

model = ModelData()
model:setName("space_station_6")
model:setMesh("ds9.model")
model:setTexture("DS9.png")
model:setSpecular("DS9Spec.png")
model:setIllumination("DS9Glow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(20)
model:setRadius(500)
model:setCollisionBox(350, 350)

model = ModelData()
model:setName("space_station_7")
model:setMesh("regula.model")
model:setTexture("Regula.png")
model:setSpecular("RegulaSpec.png")
model:setIllumination("RegulaGlow.png")
model:setRenderOffset(-20, 0, 5)
model:setScale(10)
model:setRadius(300)
model:setCollisionBox(320, 320)

model = ModelData()
model:setName("space_station_8")
model:setMesh("pbase.model")
model:setTexture("PBase.png")
model:setSpecular("PBaseSpec.png")
model:setIllumination("PBaseGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(10)
model:setRadius(300)
model:setCollisionBox(450, 450)

model = ModelData()
model:setName("EnterpriseA")
model:setMesh("ncc1701.model")
model:setTexture("fed_hr_1.png")
model:setSpecular("fed_hr_1_spec.png")
model:setIllumination("fed_hr_1_glow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(6)
model:setRadius(150)
model:setCollisionBox(150, 120)

model = ModelData()
model:setName("EnterpriseD")
model:setMesh("galaxy_again.model")
model:setTexture("Galaxy.jpg")
model:setSpecular("GalaxySpec.jpg")
model:setIllumination("GalaxyGlow.jpg")
model:setRenderOffset(0, 0, 0)
model:setScale(7)
model:setRadius(375)
model:setCollisionBox(335, 300)


model = ModelData()
model:setName("Defiant")
model:setMesh("Defiant.model")
model:setTexture("Defiant.png")
model:setSpecular("DefiantSpec.png")
model:setIllumination("DefiantGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(3)
model:setRadius(100)
model:setCollisionBox(180, 180)

model = ModelData()
model:setName("Prometheus")
model:setMesh("prometheus.model")
model:setTexture("_F_Prometheus.png")
model:setSpecular("_F_PrometheusSpec.png")
model:setIllumination("_F_PrometheusGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(6)
model:setRadius(250)
model:setCollisionBox(230, 200)


model = ModelData()
model:setName("intrepid")
model:setMesh("intrepid.model")
model:setTexture("Intrepid.png")
model:setSpecular("IntrepidSpec.png")
model:setIllumination("IntrepidGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(5)
model:setRadius(200)
model:setCollisionBox(200, 200)


--[[ Neutral or special ship types --]]

model = ModelData()
model:setName("ferengi-marauder")
model:setMesh("FerengiMarauder.model")
model:setTexture("FM_Low.png")
model:setSpecular("FM_LowSpec.png")
model:setIllumination("FM_LowGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(6)
model:setRadius(140)


-- [[ Enemy Ships --]]


model = ModelData()
model:setName("BorgCube")
model:setMesh("borgcube.model")
model:setTexture("_B_Cube.png")
model:setSpecular("_B_CubeSpec.png")
model:setIllumination("_B_CubeGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(10)
model:setRadius(200)
model:setCollisionBox(380, 380)

model = ModelData()
model:setName("BirdOfDeath")
model:setMesh("birdofdeath.model")
model:setTexture("_K_BirdOfDeath.png")
model:setSpecular("_K_BirdOfDeathSpec.png")
model:setIllumination("_K_BirdOfDeath.png")
model:setRenderOffset(0, 0, 0)
model:setScale(6)
model:setRadius(140)
model:setCollisionBox(80, 80)

model = ModelData()
model:setName("Kvek")
model:setMesh("kvek.model")
model:setTexture("_K_Kvek.png")
model:setSpecular("_K_KvekSpec.png")
model:setIllumination("_K_KvekGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(6)
model:setRadius(140)
model:setCollisionBox(80, 80)

model = ModelData()
model:setName("Bloodwing")
model:setMesh("bloodwing.model")
model:setTexture("_K_Bloodwing.png")
model:setSpecular("_K_BloodwingSpec.png")
model:setIllumination("_K_BloodwingGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(6)
model:setRadius(120)
model:setCollisionBox(120, 120)


model = ModelData()
model:setName("Vorcha")
model:setMesh("vorchall.model")
model:setTexture("Vorcha2.png")
model:setSpecular("Vorcha2Spec.png")
model:setIllumination("Vorcha2Glow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(6)
model:setRadius(140)
model:setCollisionBox(140, 140)

model = ModelData()
model:setName("KlingBirdOfPrey")
model:setMesh("kff.model")
model:setTexture("kff.png")
model:setSpecular("kff_spec.png")
model:setIllumination("kff_glow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(3)
model:setRadius(80)
model:setCollisionBox(60, 80)

model = ModelData()
model:setName("Warbird")
model:setMesh("warbird.model")
model:setTexture("Warbird.png")
model:setSpecular("WarbirdSpec.png")
model:setIllumination("WarbirdGlow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(7)
model:setRadius(140)
model:setCollisionBox(120, 140)

model = ModelData()
model:setName("RomBirdOfPrey")
model:setMesh("rlc.model")
model:setTexture("rom_hr_1.png")
model:setSpecular("rom_hr_1_spec.png")
model:setIllumination("rom_hr_1_glow.png")
model:setRenderOffset(0, 0, 0)
model:setScale(4)
model:setRadius(80)
model:setCollisionBox(140, 160)

