-- Trek Ships

model = ModelData()
model:setName("space_station_5")
model:setMesh("starbase.obj")
model:setTexture("starbase.png")
model:setSpecular("starbase_spec.png")
model:setIllumination("starbase_glow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(20)
model:setRadius(270)
model:setCollisionBox(290, 290)

model = ModelData()
model:setName("space_station_6")
model:setMesh("ds9.obj")
model:setTexture("DS9.png")
model:setSpecular("DS9Spec.png")
model:setIllumination("DS9Glow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(20)
model:setRadius(900)
model:setCollisionBox(900,900)

model = ModelData()
model:setName("space_station_7")
model:setMesh("regula.obj")
model:setTexture("Regula.png")
model:setSpecular("RegulaSpec.png")
model:setIllumination("RegulaGlow.png")
model:setRenderOffset(10, 0, 5)
model:setScale(10)
model:setRadius(200)
model:setCollisionBox(800, 800)

model = ModelData()
model:setName("space_station_8")
model:setMesh("pbase.obj")
model:setTexture("PBase.png")
model:setSpecular("PBaseSpec.png")
model:setIllumination("PBaseGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(10)
model:setRadius(300)
model:setCollisionBox(800, 800)

model = ModelData()
model:setName("EnterpriseA")
model:setMesh("ncc1701.obj")
model:setTexture("fed_hr_1.png")
model:setSpecular("fed_hr_1_spec.png")
model:setIllumination("fed_hr_1_glow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(6)
model:setRadius(200)
model:setCollisionBox(200, 200)

model = ModelData()
model:setName("EnterpriseD")
model:setMesh("galaxy_again.obj")
model:setTexture("Galaxy.jpg")
model:setSpecular("GalaxySpec.jpg")
model:setIllumination("GalaxyGlow.jpg")
model:setRenderOffset(0, 0, 5)
model:setScale(7)
model:setRadius(400)
model:setCollisionBox(400, 375)


model = ModelData()
model:setName("Defiant")
model:setMesh("Defiant.obj")
model:setTexture("Defiant.png")
model:setSpecular("DefiantSpec.png")
model:setIllumination("DefiantGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(3)
model:setRadius(200)
model:setCollisionBox(150, 150)

model = ModelData()
model:setName("Prometheus")
model:setMesh("prometheus.obj")
model:setTexture("_F_Prometheus.png")
model:setSpecular("_F_PrometheusSpec.png")
model:setIllumination("_F_PrometheusGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(6)
model:setRadius(200)
model:setCollisionBox(200, 230)


model = ModelData()
model:setName("intrepid")
model:setMesh("intrepid.obj")
model:setTexture("Intrepid.png")
model:setSpecular("IntrepidSpec.png")
model:setIllumination("IntrepidGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(5)
model:setRadius(200)
model:setCollisionBox(200, 200)


--[[ Neutral or special ship types --]]

model = ModelData()
model:setName("ferengi-marauder")
model:setMesh("FerengiMarauder.obj")
model:setTexture("FM_Low.png")
model:setSpecular("FM_LowSpec.png")
model:setIllumination("FM_LowGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(6)
model:setRadius(140)
model:setCollisionBox(120, 120)


-- [[ Enemy Ships --]]


model = ModelData()
model:setName("BorgCube")
model:setMesh("borgcube.obj")
model:setTexture("_B_Cube.png")
model:setSpecular("_B_CubeSpec.png")
model:setIllumination("_B_CubeGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(10)
model:setRadius(140)
model:setCollisionBox(120, 120)


model = ModelData()
model:setName("BirdOfDeath")
model:setMesh("birdofdeath.obj")
model:setTexture("_K_BirdOfDeath.png")
model:setSpecular("_K_BirdOfDeathSpec.png")
model:setIllumination("_K_BirdOfDeath.png")
model:setRenderOffset(0, 0, 5)
model:setScale(6)
model:setRadius(140)
model:setCollisionBox(120, 120)

model = ModelData()
model:setName("Kvek")
model:setMesh("kvek.obj")
model:setTexture("_K_Kvek.png")
model:setSpecular("_K_KvekSpec.png")
model:setIllumination("_K_KvekGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(6)
model:setRadius(140)
model:setCollisionBox(120, 120)

model = ModelData()
model:setName("Bloodwing")
model:setMesh("bloodwing.obj")
model:setTexture("_K_Bloodwing.png")
model:setSpecular("_K_BloodwingSpec.png")
model:setIllumination("_K_BloodwingGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(6)
model:setRadius(120)
model:setCollisionBox(120, 120)


model = ModelData()
model:setName("Vorcha")
model:setMesh("vorchall.obj")
model:setTexture("Vorcha2.png")
model:setSpecular("Vorcha2Spec.png")
model:setIllumination("Vorcha2Glow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(6)
model:setRadius(140)
model:setCollisionBox(140, 140)

model = ModelData()
model:setName("KlingBirdOfPrey")
model:setMesh("kff.obj")
model:setTexture("kff.png")
model:setSpecular("kff_spec.png")
model:setIllumination("kff_glow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(5)
model:setRadius(80)
model:setCollisionBox(80, 80)

model = ModelData()
model:setName("Warbird")
model:setMesh("warbird.obj")
model:setTexture("Warbird.png")
model:setSpecular("WarbirdSpec.png")
model:setIllumination("WarbirdGlow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(6)
model:setRadius(140)
model:setCollisionBox(140, 140)

model = ModelData()
model:setName("RomBirdOfPrey")
model:setMesh("rlc.obj")
model:setTexture("rom_hr_1.png")
model:setSpecular("rom_hr_1_spec.png")
model:setIllumination("rom_hr_1_glow.png")
model:setRenderOffset(0, 0, 5)
model:setScale(4)
model:setRadius(80)
model:setCollisionBox(90, 90)